name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to your FastAPI application
          push: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/fastapi-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --image=gcr.io/${{ secrets.PROJECT_ID }}/fastapi-app:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
